services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - fastapi-service

  fastapi-service:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    env_file:
      - ./backend/app/.env
    depends_on:
      - sqlite-db
    volumes:
      - shared-db:/db

  sqlite-db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    volumes:
      - shared-db:/db

volumes:
  shared-db:
