CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name TEXT NOT NULL,
    transcription TEXT NOT NULL,
    confidence_score TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);